const Types = {
    SET_CURRENCIES: 'SET_CURRENCIES',
    SET_ACTIVE_CURRENCY: 'SET_ACTIVE_CURRENCY',
    FILTER_CURRENCIES: 'FILTER_CURRENCIES',
    UPDATE_CURRENT_FILTER_VALUE: 'UPDATE_CURRENT_FILTER_VALUE',
    SET_DIFF: 'SET_DIFF',
    SET_FIRST_CURRENCY: 'SET_FIRST_CURRENCY',
    SET_SECOND_CURRENCY: 'SET_SECOND_CURRENCY',
    SET_FIRST_CURRENCY_VALUE: 'SET_FIRST_CURRENCY_VALUE',
    CALC_DIFF: 'CALC_DIFF',
    SWAP_CURRENCIES: 'SWAP_CURRENCIES'
}

export default Types